---
version: "2.0"

services:
  mimi-app:
    image: node:18-alpine
    command:
      - "sh"
      - "-c"
      - |
        npm install -g npm@latest
        npm ci
        npm run build
        npm start
    env:
      - NODE_ENV=production
      - PORT=5000
      - OPENAI_API_KEY=
      - ANTHROPIC_API_KEY=
    expose:
      - port: 5000
        as: 80
        to:
          - global: true
    resources:
      cpu:
        units: 2.0
      memory:
        size: 2Gi
      storage:
        size: 10Gi

  nginx:
    image: nginx:alpine
    command:
      - "sh"
      - "-c"
      - |
        cat > /etc/nginx/nginx.conf << 'EOF'
        events { worker_connections 1024; }
        http {
          upstream app {
            server mimi-app:5000;
          }
          server {
            listen 80;
            location / {
              proxy_pass http://app;
              proxy_set_header Host $$host;
              proxy_set_header X-Real-IP $$remote_addr;
            }
          }
        }
        EOF
        nginx -g 'daemon off;'
    expose:
      - port: 80
        as: 8080
        to:
          - global: true
    depends_on:
      - mimi-app
    resources:
      cpu:
        units: 0.5
      memory:
        size: 512Mi
      storage:
        size: 1Gi

profiles:
  compute:
    mimi-app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 2Gi
        storage:
          size: 10Gi
    nginx:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 1Gi
  placement:
    westcoast:
      attributes:
        region: us-west
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        mimi-app:
          denom: uakt
          amount: 1000
        nginx:
          denom: uakt
          amount: 500

deployment:
  mimi-app:
    westcoast:
      profile: mimi-app
      count: 1
  nginx:
    westcoast:
      profile: nginx
      count: 1