---
version: "2.0"

services:
  orderfi-app:
    image: node:18-alpine
    command:
      - "sh"
      - "-c"
      - |
        apk add --no-cache git
        git clone https://github.com/replit/orderfi-ai.git /app || echo "Using existing code"
        cd /app
        npm install
        npm run build
        npm run start:prod
    env:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://orderfi:secure_password@orderfi-db:5432/orderfi
      - AKASH_API_ENDPOINT=https://chatapi.akash.network/v1
      - BLOCKCHAIN_NETWORK=base
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
        accept:
          - orderfi.akash.network
    resources:
      cpu:
        units: 1
      memory:
        size: 1Gi
      storage:
        size: 5Gi

  orderfi-db:
    image: postgres:15-alpine
    env:
      - POSTGRES_DB=orderfi
      - POSTGRES_USER=orderfi
      - POSTGRES_PASSWORD=secure_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
      - port: 5432
        to:
          - service: orderfi-app
    resources:
      cpu:
        units: 0.5
      memory:
        size: 512Mi
      storage:
        size: 10Gi

  orderfi-redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - port: 6379
        to:
          - service: orderfi-app
    resources:
      cpu:
        units: 0.25
      memory:
        size: 256Mi
      storage:
        size: 1Gi

profiles:
  compute:
    orderfi-app:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          - size: 5Gi
            attributes:
              persistent: true
              class: beta3
    orderfi-db:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 10Gi
            attributes:
              persistent: true
              class: beta3
    orderfi-redis:
      resources:
        cpu:
          units: 0.25
        memory:
          size: 256Mi
        storage:
          - size: 1Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        orderfi-app:
          denom: uakt
          amount: 1000
        orderfi-db:
          denom: uakt
          amount: 500
        orderfi-redis:
          denom: uakt
          amount: 250

deployment:
  orderfi-app:
    dcloud:
      profile: orderfi-app
      count: 2
  orderfi-db:
    dcloud:
      profile: orderfi-db
      count: 1
  orderfi-redis:
    dcloud:
      profile: orderfi-redis
      count: 1